// frontend/src/components/sections/LabReport.jsx
import React, { useEffect, useState } from 'react';
import api from '../../api/client.js';
import useReveal from '../../hooks/useReveal.js';

export default function LabReport() {
  const [report, setReport] = useState(null);
  const [status, setStatus] = useState('loading');

  useEffect(() => {
    let active = true;
    api
      .getLabReport()
      .then((data) => {
        if (!active) return;
        setReport(data);
        setStatus('ready');
      })
      .catch(() => active && setStatus('error'));
    return () => {
      active = false;
    };
  }, []);

  useReveal([report]);

  return (
    <section id="bukti" className="sec">
      <div className="floating-droplet" style={{ left: '18%', top: '30%', animationDelay: '1.1s' }} />
      <div className="inner">
        <div className="rv">
          <span className="sec-chip">06</span>
          <span className="sec-kicker">Kualitas Teruji</span>
          <h2 className="sec-title">
            Bukti, bukan <em>janji.</em>
          </h2>
          <div className="sec-bar" />
        </div>

        {status === 'loading' && <p className="section-loading">Memuat laporan uji lab…</p>}
        {status === 'error' && (
          <p className="section-error">Gagal memuat laporan. Silakan segarkan halaman.</p>
        )}

        {status === 'ready' && report && (
          <>
            <div className="receipt rv">
              <div className="receipt-header">
                <b>OXYRA</b>
                <br />
                <span className="receipt-subtitle">Laporan Uji Laboratorium</span>
              </div>
              <div className="meta-row">
                <span>Batch</span>
                <span>{report.batch}</span>
              </div>
              <div className="meta-row">
                <span>Tanggal Uji</span>
                <span>{report.testDate}</span>
              </div>
              <div className="meta-row">
                <span>Laboratorium</span>
                <span>{report.laboratory}</span>
              </div>
              <table>
                <tbody>
                  {report.metrics.map((metric) => (
                    <tr key={metric.label}>
                      <td>{metric.label}</td>
                      <td className={metric.highlight ? 'neg' : undefined}>{metric.value}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
              <div className="meta-row">
                <span>BPOM</span>
                <span>{report.bpom}</span>
              </div>
              <div className="meta-row">
                <span>Halal BPJPH</span>
                <span>{report.halalBpjph}</span>
              </div>
              <div className="foot-note">{report.footNote}</div>
              {report.isIllustrative && <div className="stamp-mark">ILUSTRASI</div>}
            </div>
            <p className="disclaimer-note">{report.disclaimer}</p>
          </>
        )}
      </div>
    </section>
  );
}

// frontend/src/app/sections/lab-report.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ApiService } from '../core/api.service';
import { LabReport } from '../core/models';
import { RevealDirective } from '../shared/reveal.directive';

type Status = 'loading' | 'ready' | 'error';

@Component({
  selector: 'app-lab-report',
  standalone: true,
  imports: [CommonModule, RevealDirective],
  templateUrl: './lab-report.component.html',
})
export class LabReportComponent implements OnInit {
  readonly report = signal<LabReport | null>(null);
  readonly status = signal<Status>('loading');

  constructor(private readonly api: ApiService) {}

  ngOnInit(): void {
    this.api.getLabReport().subscribe({
      next: (data) => {
        this.report.set(data);
        this.status.set('ready');
      },
      error: () => this.status.set('error'),
    });
  }
}

<section id="bukti" class="sec">
  <div class="floating-droplet" style="left: 18%; top: 30%; animation-delay: 1.1s;"></div>
  <div class="inner">
    <div class="rv">
      <span class="sec-chip">06</span>
      <span class="sec-kicker">Kualitas Teruji</span>
      <h2 class="sec-title">Bukti, bukan <em>janji.</em></h2>
      <div class="sec-bar"></div>
    </div>

    <p class="section-loading" *ngIf="status() === 'loading'">Memuat laporan uji lab…</p>
    <p class="section-error" *ngIf="status() === 'error'">Gagal memuat laporan. Silakan segarkan halaman.</p>

    <ng-container *ngIf="status() === 'ready' && report() as r">
      <div class="receipt rv">
        <div class="receipt-header">
          <b>OXYRA</b>
          <br />
          <span class="receipt-subtitle">Laporan Uji Laboratorium</span>
        </div>
        <div class="meta-row"><span>Batch</span><span>{{ r.batch }}</span></div>
        <div class="meta-row"><span>Tanggal Uji</span><span>{{ r.testDate }}</span></div>
        <div class="meta-row"><span>Laboratorium</span><span>{{ r.laboratory }}</span></div>
        <table>
          <tbody>
            <tr *ngFor="let metric of r.metrics">
              <td>{{ metric.label }}</td>
              <td [class.neg]="metric.highlight">{{ metric.value }}</td>
            </tr>
          </tbody>
        </table>
        <div class="meta-row"><span>BPOM</span><span>{{ r.bpom }}</span></div>
        <div class="meta-row"><span>Halal BPJPH</span><span>{{ r.halalBpjph }}</span></div>
        <div class="foot-note">{{ r.footNote }}</div>
        <div class="stamp-mark" *ngIf="r.isIllustrative">ILUSTRASI</div>
      </div>
      <p class="disclaimer-note">{{ r.disclaimer }}</p>
    </ng-container>
  </div>
</section>
