// frontend/src/components/sections/Relief.jsx
import React, { useRef } from 'react';
import useDropfieldCanvas from '../../hooks/useDropfieldCanvas.js';
import { FLAKE_IMAGE_SRC } from '../../assets/flakeImage.js';

/**
 * @param {{ crystallized: boolean }} props
 */
export default function Relief({ crystallized }) {
  const sectionRef = useRef(null);
  const canvasRef = useRef(null);
  const flakeRef = useRef(null);

  useDropfieldCanvas(canvasRef, sectionRef, flakeRef);

  return (
    <section
      id="relief"
      ref={sectionRef}
      className={`sec snap-sec${crystallized ? ' crystallized' : ''}`}
    >
      <canvas id="wonder-canvas" ref={canvasRef} />

      <div className="wonder-badge" id="wonder-badge">
        ❄️ Tetesan air menyelaraskan diri menjadi kristal OXYRA
      </div>

      <div className="floating-bubbles" id="interactive-bubbles">
        <div className="bubble" style={{ width: 32, height: 32, left: '16%', animationDelay: '0s', animationDuration: '7s' }} />
        <div className="bubble" style={{ width: 20, height: 20, left: '30%', animationDelay: '2s', animationDuration: '9s' }} />
        <div className="bubble" style={{ width: 44, height: 44, left: '68%', animationDelay: '1s', animationDuration: '8s' }} />
        <div className="bubble" style={{ width: 24, height: 24, left: '84%', animationDelay: '3s', animationDuration: '6s' }} />
      </div>

      <div className="decor splash-r" aria-hidden="true">
        <img src="https://i.imgur.com/SKOAvML.png" alt="Oxyra Vertical Water Splash" />
      </div>

      <img id="flakeimg" ref={flakeRef} src={FLAKE_IMAGE_SRC} alt="" />

      <div className="brand-name">OXYRA</div>
      <p className="era-line">Welcome to the Happy Hydration Era</p>
      <p className="sub-line">
        Tetap terhidrasi setiap hari dengan pengalaman minum yang lebih menyenangkan.
      </p>

      <div className="hydro-pool-wrap" aria-hidden="true">
        <div className="hydro-droplet" />
        <div className="pool-ripples">
          <i />
          <i />
          <i />
        </div>
      </div>
    </section>
  );
}

// frontend/src/app/sections/relief.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  Input,
  OnDestroy,
  ViewChild,
} from '@angular/core';
import { DropfieldAnimation } from '../shared/dropfield-animation';
import { ScrollPhysicsService } from '../core/scroll-physics.service';

@Component({
  selector: 'app-relief',
  standalone: true,
  templateUrl: './relief.component.html',
})
export class ReliefComponent implements AfterViewInit, OnDestroy {
  @Input() crystallized = false;

  @ViewChild('reliefSection', { static: true }) sectionRef!: ElementRef<HTMLElement>;
  @ViewChild('wonderCanvas', { static: true }) canvasRef!: ElementRef<HTMLCanvasElement>;
  @ViewChild('flakeImg', { static: true }) flakeRef!: ElementRef<HTMLImageElement>;

  private animation?: DropfieldAnimation;

  constructor(readonly scrollPhysics: ScrollPhysicsService) {}

  ngAfterViewInit(): void {
    this.animation = new DropfieldAnimation(
      this.canvasRef.nativeElement,
      this.sectionRef.nativeElement,
      this.flakeRef.nativeElement
    );
    this.animation.start();
  }

  ngOnDestroy(): void {
    this.animation?.destroy();
  }
}

<section id="relief" #reliefSection class="sec snap-sec" [class.crystallized]="crystallized">
  <canvas id="wonder-canvas" #wonderCanvas></canvas>

  <div class="wonder-badge" id="wonder-badge">
    ❄️ Tetesan air menyelaraskan diri menjadi kristal OXYRA
  </div>

  <div class="floating-bubbles" id="interactive-bubbles">
    <div class="bubble" style="width: 32px; height: 32px; left: 16%; animation-delay: 0s; animation-duration: 7s;"></div>
    <div class="bubble" style="width: 20px; height: 20px; left: 30%; animation-delay: 2s; animation-duration: 9s;"></div>
    <div class="bubble" style="width: 44px; height: 44px; left: 68%; animation-delay: 1s; animation-duration: 8s;"></div>
    <div class="bubble" style="width: 24px; height: 24px; left: 84%; animation-delay: 3s; animation-duration: 6s;"></div>
  </div>

  <div class="decor splash-r" aria-hidden="true">
    <img src="https://i.imgur.com/SKOAvML.png" alt="Oxyra Vertical Water Splash" />
  </div>

  <img
    id="flakeimg"
    #flakeImg
    src="/images/store/oxyra-flake.jpg"
    alt="Kristal salju heksagonal OXYRA"
  />

  <div class="brand-name">OXYRA</div>
  <p class="era-line">Welcome to the Happy Hydration Era</p>
  <p class="sub-line">Tetap terhidrasi setiap hari dengan pengalaman minum yang lebih menyenangkan.</p>

  <div class="hydro-pool-wrap" aria-hidden="true">
    <div class="hydro-droplet"></div>
    <div class="pool-ripples">
      <i></i>
      <i></i>
      <i></i>
    </div>
  </div>
</section>
