// frontend/src/components/sections/WhyOxyra.jsx
import React, { useEffect, useState } from 'react';
import api from '../../api/client.js';
import Icon from '../common/Icon.jsx';
import useReveal from '../../hooks/useReveal.js';

export default function WhyOxyra() {
  const [reasons, setReasons] = useState([]);
  const [status, setStatus] = useState('loading');

  useEffect(() => {
    let active = true;
    api
      .getWhyOxyra()
      .then((data) => {
        if (!active) return;
        setReasons(data);
        setStatus('ready');
      })
      .catch(() => active && setStatus('error'));
    return () => {
      active = false;
    };
  }, []);

  useReveal([reasons]);

  return (
    <section id="kenapa" className="sec">
      <div className="hex-bg" />
      <div className="subtle-splash-bg" style={{ left: '-6%', top: '18%', width: 320 }}>
        <img src="https://i.imgur.com/SKOAvML.png" alt="" />
      </div>
      <div className="floating-droplet" style={{ right: '15%', top: '20%', animationDelay: '1.8s' }} />
      <div
        className="floating-droplet"
        style={{ left: '20%', bottom: '15%', width: 16, height: 20, animationDelay: '4.2s' }}
      />

      <div className="inner">
        <div className="rv">
          <span className="sec-chip">02</span>
          <span className="sec-kicker">Kenapa Oxyra</span>
          <h2 className="sec-title">
            Dibuat untuk <em>hidup yang bergerak.</em>
          </h2>
          <div className="sec-bar" />
        </div>

        {status === 'loading' && <p className="section-loading">Memuat alasan memilih OXYRA…</p>}
        {status === 'error' && (
          <p className="section-error">Gagal memuat konten. Silakan segarkan halaman.</p>
        )}

        {status === 'ready' && (
          <div className="why-grid">
            {reasons.map((reason) => (
              <div className="why-card rv" key={reason.id}>
                <Icon name={reason.icon} />
                <h3>{reason.title}</h3>
                <p>{reason.description}</p>
              </div>
            ))}
          </div>
        )}
      </div>
    </section>
  );
}

// frontend/src/app/sections/why-oxyra.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ApiService } from '../core/api.service';
import { WhyReason } from '../core/models';
import { RevealDirective } from '../shared/reveal.directive';
import { IconComponent } from '../shared/icon.component';
import { SkeletonCardComponent } from '../shared/skeleton-card.component';

type Status = 'loading' | 'ready' | 'error';

@Component({
  selector: 'app-why-oxyra',
  standalone: true,
  imports: [CommonModule, RevealDirective, IconComponent, SkeletonCardComponent],
  templateUrl: './why-oxyra.component.html',
})
export class WhyOxyraComponent implements OnInit {
  readonly reasons = signal<WhyReason[]>([]);
  readonly status = signal<Status>('loading');

  constructor(private readonly api: ApiService) {}

  ngOnInit(): void {
    this.api.getWhyOxyra().subscribe({
      next: (data) => {
        this.reasons.set(data);
        this.status.set('ready');
      },
      error: () => this.status.set('error'),
    });
  }
}

<section id="kenapa" class="sec">
  <div class="hex-bg"></div>
  <div class="subtle-splash-bg" style="left: -6%; top: 18%; width: 320px;">
    <img src="https://i.imgur.com/SKOAvML.png" alt="" />
  </div>
  <div class="floating-droplet" style="right: 15%; top: 20%; animation-delay: 1.8s;"></div>
  <div class="floating-droplet" style="left: 20%; bottom: 15%; width: 16px; height: 20px; animation-delay: 4.2s;"></div>

  <div class="inner">
    <div class="rv">
      <span class="sec-chip">02</span>
      <span class="sec-kicker">Kenapa Oxyra</span>
      <h2 class="sec-title">Dibuat untuk <em>hidup yang bergerak.</em></h2>
      <div class="sec-bar"></div>
    </div>

    <app-skeleton-card *ngIf="status() === 'loading'" [count]="4" variant="product"></app-skeleton-card>
    <p class="section-error" *ngIf="status() === 'error'">Gagal memuat konten. Silakan segarkan halaman.</p>

    <div class="why-grid" *ngIf="status() === 'ready'">
      <div class="why-card rv" *ngFor="let reason of reasons()">
        <app-icon [name]="reason.icon"></app-icon>
        <h3>{{ reason.title }}</h3>
        <p>{{ reason.description }}</p>
      </div>
    </div>
  </div>
</section>
