// frontend/src/app/shared/navbar/navbar.component.ts
import { Component, EventEmitter, Input, Output, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Brand } from '../../core/models';
import { CartService } from '../../core/cart.service';
import { ThemeService } from '../../core/theme.service';
import { I18nService } from '../../core/i18n.service';

interface NavLink {
  href: string;
  key: string;
}

const NAV_LINKS: NavLink[] = [
  { href: '#hot', key: 'nav.home' },
  { href: '#kenapa', key: 'nav.why' },
  { href: '#produk', key: 'nav.products' },
  { href: '#club', key: 'nav.community' },
  { href: '#toko', key: 'nav.store' },
  { href: '#bukti', key: 'nav.lab' },
  { href: '#testimoni', key: 'nav.testimonials' },
];

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './navbar.component.html',
})
export class NavbarComponent {
  @Input({ required: true }) brand!: Brand;
  @Output() openCart = new EventEmitter<void>();

  readonly navLinks = NAV_LINKS;
  readonly mobileOpen = signal(false);

  constructor(
    readonly cart: CartService,
    readonly themeService: ThemeService,
    readonly i18n: I18nService
  ) {}

  toggleMobileMenu(): void {
    this.mobileOpen.update((v) => !v);
  }

  closeMobileMenu(): void {
    this.mobileOpen.set(false);
  }
}

<nav class="navbar">
  <a href="#hot" class="nav-brand">
    <img [src]="brand.logoUrl" alt="OXYRA" class="nav-logo-img" />
    <span class="nav-brand-text">{{ brand.name }}</span>
  </a>

  <ul class="nav-links">
    <li *ngFor="let link of navLinks">
      <a [href]="link.href">{{ i18n.t(link.key) }}</a>
    </li>
  </ul>

  <div class="nav-actions">
    <button
      type="button"
      class="theme-toggle-btn"
      (click)="i18n.toggleLanguage()"
      aria-label="Ganti bahasa"
      [title]="i18n.language() === 'id' ? 'Switch to English' : 'Ganti ke Bahasa Indonesia'"
    >
      {{ i18n.language() === 'id' ? '🇮🇩' : '🇬🇧' }}
    </button>

    <button
      type="button"
      class="theme-toggle-btn"
      (click)="themeService.toggleTheme()"
      [attr.aria-label]="themeService.theme() === 'dark' ? i18n.t('theme.light') : i18n.t('theme.dark')"
      [title]="themeService.theme() === 'dark' ? i18n.t('theme.light') : i18n.t('theme.dark')"
    >
      {{ themeService.theme() === 'dark' ? '☀️' : '🌙' }}
    </button>

    <button type="button" class="cart-nav-btn" (click)="openCart.emit()" [attr.aria-label]="i18n.t('cart.title')">
      🛒
      <span class="cart-nav-badge" *ngIf="cart.totalItems() > 0">{{ cart.totalItems() }}</span>
    </button>

    <a [href]="brand.whatsapp.link" class="nav-cta" target="_blank" rel="noopener noreferrer">
      {{ i18n.t('nav.orderWa') }}
    </a>

    <button
      type="button"
      class="nav-hamburger"
      [class.is-open]="mobileOpen()"
      (click)="toggleMobileMenu()"
      aria-label="Buka menu"
      [attr.aria-expanded]="mobileOpen()"
    >
      <span></span>
      <span></span>
      <span></span>
    </button>
  </div>

  <div class="nav-links-mobile" [class.is-open]="mobileOpen()">
    <a *ngFor="let link of navLinks" [href]="link.href" (click)="closeMobileMenu()">
      {{ i18n.t(link.key) }}
    </a>
  </div>
</nav>

// frontend/src/components/common/Navbar.jsx
import React from 'react';

/**
 * @param {{ brand: { name: string, logoUrl: string, whatsapp: { link: string } } }} props
 */
export default function Navbar({ brand }) {
  return (
    <nav className="navbar">
      <a href="#hot" className="nav-brand">
        <img src={brand.logoUrl} alt="OXYRA" className="nav-logo-img" />
        <span className="nav-brand-text">{brand.name}</span>
      </a>
      <ul className="nav-links">
        <li>
          <a href="#hot">Home</a>
        </li>
        <li>
          <a href="#kenapa">Kenapa</a>
        </li>
        <li>
          <a href="#produk">Produk &amp; Harga</a>
        </li>
        <li>
          <a href="#club">Komunitas</a>
        </li>
        <li>
          <a href="#bukti">Uji Lab</a>
        </li>
        <li>
          <a href="#testimoni">Testimoni</a>
        </li>
      </ul>
      <a href={brand.whatsapp.link} className="nav-cta" target="_blank" rel="noopener noreferrer">
        Pesan WA
      </a>
    </nav>
  );
}
