// frontend/src/app/sections/club.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ApiService } from '../core/api.service';
import { Club } from '../core/models';
import { RevealDirective } from '../shared/reveal.directive';
import { SkeletonCardComponent } from '../shared/skeleton-card.component';

type Status = 'loading' | 'ready' | 'error';

@Component({
  selector: 'app-club',
  standalone: true,
  imports: [CommonModule, RevealDirective, SkeletonCardComponent],
  templateUrl: './club.component.html',
})
export class ClubComponent implements OnInit {
  readonly club = signal<Club | null>(null);
  readonly status = signal<Status>('loading');

  constructor(private readonly api: ApiService) {}

  ngOnInit(): void {
    this.api.getClub().subscribe({
      next: (data) => {
        this.club.set(data);
        this.status.set('ready');
      },
      error: () => this.status.set('error'),
    });
  }
}

<section id="club" class="sec">
  <div class="speed-lines" aria-hidden="true"></div>
  <div class="floating-droplet" style="left: 15%; top: 25%; animation-delay: 1.5s;"></div>
  <div class="floating-droplet" style="right: 18%; bottom: 10%; width: 18px; height: 22px; animation-delay: 3.8s;"></div>

  <div class="inner">
    <div class="rv">
      <span class="sec-chip">04</span>
      <span class="sec-kicker">Happy Hydration Club</span>
      <h2 class="sec-title">Every Drop. <em>Every Move.</em></h2>
      <div class="sec-bar"></div>
    </div>

    <app-skeleton-card *ngIf="status() === 'loading'" [count]="5" variant="product"></app-skeleton-card>
    <p class="section-error" *ngIf="status() === 'error'">Gagal memuat konten. Silakan segarkan halaman.</p>

    <ng-container *ngIf="status() === 'ready' && club() as c">
      <div class="club-hero rv">
        <img [src]="c.heroImage" alt="OXYRA Happy Hydration Club Lifestyle" loading="lazy" />
        <div class="club-hero-badge">{{ c.heroBadge }}</div>
      </div>

      <p class="club-intro rv">{{ c.intro }}</p>

      <div class="activity-grid">
        <div class="act-card rv" *ngFor="let activity of c.activities">
          <span class="act-emoji">{{ activity.emoji }}</span>
          <h3>{{ activity.title }}</h3>
          <p>{{ activity.description }}</p>
        </div>
      </div>

      <div class="benefits-strip rv">
        <div class="ben-pill" *ngFor="let benefit of c.benefits">
          <b>{{ benefit.title }}</b>
          <span>{{ benefit.description }}</span>
        </div>
      </div>
    </ng-container>
  </div>
</section>

// frontend/src/components/sections/Club.jsx
import React, { useEffect, useState } from 'react';
import api from '../../api/client.js';
import useReveal from '../../hooks/useReveal.js';

export default function Club() {
  const [club, setClub] = useState(null);
  const [status, setStatus] = useState('loading');

  useEffect(() => {
    let active = true;
    api
      .getClub()
      .then((data) => {
        if (!active) return;
        setClub(data);
        setStatus('ready');
      })
      .catch(() => active && setStatus('error'));
    return () => {
      active = false;
    };
  }, []);

  useReveal([club]);

  return (
    <section id="club" className="sec">
      <div className="speed-lines" aria-hidden="true" />
      <div className="floating-droplet" style={{ left: '15%', top: '25%', animationDelay: '1.5s' }} />
      <div
        className="floating-droplet"
        style={{ right: '18%', bottom: '10%', width: 18, height: 22, animationDelay: '3.8s' }}
      />

      <div className="inner">
        <div className="rv">
          <span className="sec-chip">04</span>
          <span className="sec-kicker">Happy Hydration Club</span>
          <h2 className="sec-title">
            Every Drop. <em>Every Move.</em>
          </h2>
          <div className="sec-bar" />
        </div>

        {status === 'loading' && <p className="section-loading">Memuat komunitas…</p>}
        {status === 'error' && (
          <p className="section-error">Gagal memuat konten. Silakan segarkan halaman.</p>
        )}

        {status === 'ready' && club && (
          <>
            <div className="club-hero rv">
              <img src={club.heroImage} alt="OXYRA Happy Hydration Club Lifestyle" />
              <div className="club-hero-badge">{club.heroBadge}</div>
            </div>

            <p className="club-intro rv">{club.intro}</p>

            <div className="activity-grid">
              {club.activities.map((activity) => (
                <div className="act-card rv" key={activity.id}>
                  <span className="act-emoji">{activity.emoji}</span>
                  <h3>{activity.title}</h3>
                  <p>{activity.description}</p>
                </div>
              ))}
            </div>

            <div className="benefits-strip rv">
              {club.benefits.map((benefit) => (
                <div className="ben-pill" key={benefit.id}>
                  <b>{benefit.title}</b>
                  <span>{benefit.description}</span>
                </div>
              ))}
            </div>
          </>
        )}
      </div>
    </section>
  );
}
