// frontend/src/app/sections/products.component.ts
import { Component, OnInit, computed, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { forkJoin } from 'rxjs';
import { ApiService } from '../core/api.service';
import { Product, ProductCategory } from '../core/models';
import { CartService } from '../core/cart.service';
import { ToastService } from '../core/toast.service';
import { I18nService } from '../core/i18n.service';
import { RevealDirective } from '../shared/reveal.directive';
import { SkeletonCardComponent } from '../shared/skeleton-card.component';

type Status = 'loading' | 'ready' | 'error';

@Component({
  selector: 'app-products',
  standalone: true,
  imports: [CommonModule, RevealDirective, SkeletonCardComponent],
  templateUrl: './products.component.html',
})
export class ProductsComponent implements OnInit {
  readonly products = signal<Product[]>([]);
  readonly categories = signal<ProductCategory[]>([]);
  readonly activeTab = signal('all');
  readonly status = signal<Status>('loading');

  readonly visibleProducts = computed(() => {
    const tab = this.activeTab();
    const all = this.products();
    return tab === 'all' ? all : all.filter((p) => p.category === tab);
  });

  constructor(
    private readonly api: ApiService,
    readonly cart: CartService,
    private readonly toast: ToastService,
    readonly i18n: I18nService
  ) {}

  ngOnInit(): void {
    forkJoin({ products: this.api.getProducts(), categories: this.api.getCategories() }).subscribe({
      next: ({ products, categories }) => {
        this.products.set(products);
        this.categories.set(categories);
        this.status.set('ready');
      },
      error: () => this.status.set('error'),
    });
  }

  setTab(tabId: string): void {
    this.activeTab.set(tabId);
  }

  handleAddToCart(product: Product): void {
    this.cart.addItem(product, 1);
    this.toast.show(`${product.name} ditambahkan ke ${this.i18n.t('cart.title').toLowerCase()}!`);
  }
}

<section id="produk" class="sec">
  <div class="hex-bg"></div>
  <div class="subtle-splash-bg" style="right: -4%; top: 25%; width: 340px; transform: scaleX(-1);">
    <img src="https://i.imgur.com/SKOAvML.png" alt="" />
  </div>
  <div class="floating-droplet" style="left: 10%; top: 12%; animation-delay: 0.8s;"></div>
  <div class="floating-droplet" style="right: 14%; bottom: 20%; animation-delay: 2.9s;"></div>

  <div class="inner">
    <div class="rv">
      <span class="sec-chip">03</span>
      <span class="sec-kicker">Daftar Produk</span>
      <h2 class="sec-title">Produk &amp; <em>Harga Resmi</em></h2>
      <div class="sec-bar"></div>
    </div>

    <app-skeleton-card *ngIf="status() === 'loading'" [count]="6" variant="product"></app-skeleton-card>
    <p class="section-error" *ngIf="status() === 'error'">Gagal memuat katalog. Silakan segarkan halaman.</p>

    <ng-container *ngIf="status() === 'ready'">
      <div class="product-tabs rv">
        <button
          type="button"
          *ngFor="let cat of categories()"
          class="tab-btn"
          [class.active]="activeTab() === cat.id"
          (click)="setTab(cat.id)"
        >
          {{ cat.label }}
        </button>
      </div>

      <div class="product-grid">
        <div class="product-card rv" [attr.data-cat]="product.category" *ngFor="let product of visibleProducts()">
          <div class="product-card-media">
            <img *ngIf="product.image" [src]="product.image" [alt]="product.name" loading="lazy" />
            <div class="product-card-placeholder" *ngIf="!product.image" aria-hidden="true">💧</div>
            <span
              class="p-badge product-card-badge"
              [class.best]="product.badgeVariant === 'best'"
              [class.tera]="product.badgeVariant === 'tera'"
            >
              {{ product.badge }}
            </span>
          </div>

          <div class="product-card-body">
            <h3>{{ product.name }}</h3>
            <p class="p-vol">{{ product.volumeLabel }}</p>
            <div class="p-price">
              {{ product.priceLabel }} <span class="p-unit">{{ product.unit }}</span>
            </div>
            <p class="p-desc">{{ product.description }}</p>
          </div>

          <div class="product-card-actions">
            <button type="button" class="card-add-btn" (click)="handleAddToCart(product)">
              {{ i18n.t('cart.addToCart') }}
            </button>
            <a
              [href]="product.orderLink"
              class="card-wa-btn"
              target="_blank"
              rel="noopener noreferrer"
              [attr.aria-label]="'Pesan ' + product.name + ' langsung via WhatsApp'"
            >
              WA →
            </a>
          </div>
        </div>
      </div>
    </ng-container>
  </div>
</section>

// frontend/src/components/sections/Products.jsx
import React, { useEffect, useState } from 'react';
import api from '../../api/client.js';
import useReveal from '../../hooks/useReveal.js';

export default function Products() {
  const [products, setProducts] = useState([]);
  const [categories, setCategories] = useState([]);
  const [activeTab, setActiveTab] = useState('all');
  const [status, setStatus] = useState('loading');

  useEffect(() => {
    let active = true;
    Promise.all([api.getProducts(), api.getCategories()])
      .then(([productData, categoryData]) => {
        if (!active) return;
        setProducts(productData);
        setCategories(categoryData);
        setStatus('ready');
      })
      .catch(() => active && setStatus('error'));
    return () => {
      active = false;
    };
  }, []);

  useReveal([products, activeTab]);

  const visibleProducts =
    activeTab === 'all' ? products : products.filter((p) => p.category === activeTab);

  return (
    <section id="produk" className="sec">
      <div className="hex-bg" />
      <div
        className="subtle-splash-bg"
        style={{ right: '-4%', top: '25%', width: 340, transform: 'scaleX(-1)' }}
      >
        <img src="https://i.imgur.com/SKOAvML.png" alt="" />
      </div>
      <div className="floating-droplet" style={{ left: '10%', top: '12%', animationDelay: '0.8s' }} />
      <div
        className="floating-droplet"
        style={{ right: '14%', bottom: '20%', animationDelay: '2.9s' }}
      />

      <div className="inner">
        <div className="rv">
          <span className="sec-chip">03</span>
          <span className="sec-kicker">Daftar Produk</span>
          <h2 className="sec-title">
            Produk &amp; <em>Harga Resmi</em>
          </h2>
          <div className="sec-bar" />
        </div>

        {status === 'loading' && <p className="section-loading">Memuat katalog produk…</p>}
        {status === 'error' && (
          <p className="section-error">Gagal memuat katalog. Silakan segarkan halaman.</p>
        )}

        {status === 'ready' && (
          <>
            <div className="product-tabs rv">
              {categories.map((cat) => (
                <button
                  key={cat.id}
                  type="button"
                  className={`tab-btn${activeTab === cat.id ? ' active' : ''}`}
                  onClick={() => setActiveTab(cat.id)}
                >
                  {cat.label}
                </button>
              ))}
            </div>

            <div className="product-grid">
              {visibleProducts.map((product) => (
                <div className="product-card rv" data-cat={product.category} key={product.id}>
                  <div>
                    <span className={`p-badge${product.badgeVariant !== 'default' ? ` ${product.badgeVariant}` : ''}`}>
                      {product.badge}
                    </span>
                    <h3>{product.name}</h3>
                    <p className="p-vol">{product.volumeLabel}</p>
                    <div className="p-price">
                      {product.priceLabel} <span className="p-unit">{product.unit}</span>
                    </div>
                    <p className="p-desc">{product.description}</p>
                  </div>
                  <a href={product.orderLink} className="card-wa-btn" target="_blank" rel="noopener noreferrer">
                    Pesan Sekarang →
                  </a>
                </div>
              ))}
            </div>
          </>
        )}
      </div>
    </section>
  );
}
