// frontend/src/app/sections/testimonials.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ApiService } from '../core/api.service';
import { Testimonial } from '../core/models';
import { RevealDirective } from '../shared/reveal.directive';
import { SkeletonCardComponent } from '../shared/skeleton-card.component';

type Status = 'loading' | 'ready' | 'error';

@Component({
  selector: 'app-testimonials',
  standalone: true,
  imports: [CommonModule, RevealDirective, SkeletonCardComponent],
  templateUrl: './testimonials.component.html',
})
export class TestimonialsComponent implements OnInit {
  readonly testimonials = signal<Testimonial[]>([]);
  readonly status = signal<Status>('loading');

  constructor(private readonly api: ApiService) {}

  ngOnInit(): void {
    this.api.getTestimonials().subscribe({
      next: (data) => {
        this.testimonials.set(data);
        this.status.set('ready');
      },
      error: () => this.status.set('error'),
    });
  }

  stars(rating: number): string {
    return '⭐'.repeat(rating);
  }
}

<section id="testimoni" class="sec">
  <div class="subtle-splash-bg" style="left: -5%; bottom: 15%; width: 300px;">
    <img src="https://i.imgur.com/SKOAvML.png" alt="" />
  </div>
  <div class="floating-droplet" style="right: 25%; top: 15%; animation-delay: 2.3s;"></div>

  <div class="inner">
    <div class="rv">
      <span class="sec-chip">05</span>
      <span class="sec-kicker">Testimoni</span>
      <h2 class="sec-title">Kata <em>Mereka</em></h2>
      <div class="sec-bar"></div>
    </div>

    <app-skeleton-card *ngIf="status() === 'loading'" [count]="3" variant="product"></app-skeleton-card>
    <p class="section-error" *ngIf="status() === 'error'">Gagal memuat testimoni. Silakan segarkan halaman.</p>

    <div class="testi-grid" *ngIf="status() === 'ready'">
      <div class="testi-card rv" *ngFor="let testimonial of testimonials()">
        <div class="stars">{{ stars(testimonial.rating) }}</div>
        <p class="testi-quote">&ldquo;{{ testimonial.quote }}&rdquo;</p>
        <div class="testi-author">{{ testimonial.author }}</div>
        <div class="testi-loc">{{ testimonial.location }}</div>
      </div>
    </div>
  </div>
</section>

// frontend/src/components/sections/Testimonials.jsx
import React, { useEffect, useState } from 'react';
import api from '../../api/client.js';
import useReveal from '../../hooks/useReveal.js';

export default function Testimonials() {
  const [testimonials, setTestimonials] = useState([]);
  const [status, setStatus] = useState('loading');

  useEffect(() => {
    let active = true;
    api
      .getTestimonials()
      .then((data) => {
        if (!active) return;
        setTestimonials(data);
        setStatus('ready');
      })
      .catch(() => active && setStatus('error'));
    return () => {
      active = false;
    };
  }, []);

  useReveal([testimonials]);

  return (
    <section id="testimoni" className="sec">
      <div className="subtle-splash-bg" style={{ left: '-5%', bottom: '15%', width: 300 }}>
        <img src="https://i.imgur.com/SKOAvML.png" alt="" />
      </div>
      <div className="floating-droplet" style={{ right: '25%', top: '15%', animationDelay: '2.3s' }} />

      <div className="inner">
        <div className="rv">
          <span className="sec-chip">05</span>
          <span className="sec-kicker">Testimoni</span>
          <h2 className="sec-title">
            Kata <em>Mereka</em>
          </h2>
          <div className="sec-bar" />
        </div>

        {status === 'loading' && <p className="section-loading">Memuat testimoni…</p>}
        {status === 'error' && (
          <p className="section-error">Gagal memuat testimoni. Silakan segarkan halaman.</p>
        )}

        {status === 'ready' && (
          <div className="testi-grid">
            {testimonials.map((testimonial) => (
              <div className="testi-card rv" key={testimonial.id}>
                <div className="stars">{'⭐'.repeat(testimonial.rating)}</div>
                <p className="testi-quote">“{testimonial.quote}”</p>
                <div className="testi-author">{testimonial.author}</div>
                <div className="testi-loc">{testimonial.location}</div>
              </div>
            ))}
          </div>
        )}
      </div>
    </section>
  );
}
