// frontend/src/app/app.component.ts
import { AfterViewInit, Component, OnDestroy, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';

import { ApiService } from './core/api.service';
import { Brand } from './core/models';
import { FALLBACK_BRAND } from './core/fallback-data';
import { ScrollPhysicsService } from './core/scroll-physics.service';

import { NavbarComponent } from './shared/navbar/navbar.component';
import { InstrumentsComponent } from './shared/instruments.component';
import { SnapDotsComponent } from './shared/snap-dots.component';
import { FooterComponent } from './shared/footer.component';
import { CartDrawerComponent } from './shared/cart-drawer/cart-drawer.component';
import { CheckoutModalComponent } from './shared/checkout-modal/checkout-modal.component';
import { ToastStackComponent } from './shared/toast-stack.component';

import { HotComponent } from './sections/hot.component';
import { DryComponent } from './sections/dry.component';
import { TurnComponent } from './sections/turn.component';
import { ReliefComponent } from './sections/relief.component';
import { ManifestoComponent } from './sections/manifesto.component';
import { WhyOxyraComponent } from './sections/why-oxyra.component';
import { ProductsComponent } from './sections/products.component';
import { ClubComponent } from './sections/club.component';
import { StoreVisitComponent } from './sections/store-visit.component';
import { TestimonialsComponent } from './sections/testimonials.component';
import { LabReportComponent } from './sections/lab-report.component';
import { DeliveryComponent } from './sections/delivery.component';
import { ClosingComponent } from './sections/closing.component';

@Component({
  selector: 'oxyra-root',
  standalone: true,
  imports: [
    CommonModule,
    NavbarComponent,
    InstrumentsComponent,
    SnapDotsComponent,
    FooterComponent,
    CartDrawerComponent,
    CheckoutModalComponent,
    ToastStackComponent,
    HotComponent,
    DryComponent,
    TurnComponent,
    ReliefComponent,
    ManifestoComponent,
    WhyOxyraComponent,
    ProductsComponent,
    ClubComponent,
    StoreVisitComponent,
    TestimonialsComponent,
    LabReportComponent,
    DeliveryComponent,
    ClosingComponent,
  ],
  templateUrl: './app.component.html',
})
export class AppComponent implements OnInit, AfterViewInit, OnDestroy {
  readonly brand = signal<Brand>(FALLBACK_BRAND);
  readonly cartOpen = signal(false);
  readonly checkoutOpen = signal(false);

  constructor(
    private readonly api: ApiService,
    readonly scrollPhysics: ScrollPhysicsService
  ) {}

  ngOnInit(): void {
    this.api.getBrand().subscribe((brand) => {
      this.brand.set(brand);
      document.title = `${brand.name} — ${brand.tagline}`;
    });
  }

  ngAfterViewInit(): void {
    this.scrollPhysics.start();
  }

  ngOnDestroy(): void {
    this.scrollPhysics.stop();
  }

  openCart(): void {
    this.cartOpen.set(true);
  }

  closeCart(): void {
    this.cartOpen.set(false);
  }

  openCheckout(): void {
    this.cartOpen.set(false);
    this.checkoutOpen.set(true);
  }

  closeCheckout(): void {
    this.checkoutOpen.set(false);
  }
}

<app-navbar [brand]="brand()" (openCart)="openCart()"></app-navbar>
<app-instruments [temperature]="scrollPhysics.temperature()" [gaugePercent]="scrollPhysics.gaugePercent()"></app-instruments>
<app-snap-dots [activeSection]="scrollPhysics.activeSection()" [visible]="scrollPhysics.dotsVisible()"></app-snap-dots>

<main>
  <app-hot></app-hot>
  <app-dry></app-dry>
  <app-turn></app-turn>
  <app-relief [crystallized]="scrollPhysics.crystallized()"></app-relief>
  <app-manifesto></app-manifesto>
  <app-why-oxyra></app-why-oxyra>
  <app-products></app-products>
  <app-club></app-club>
  <app-store-visit [brand]="brand()"></app-store-visit>
  <app-testimonials></app-testimonials>
  <app-lab-report></app-lab-report>
  <app-delivery [brand]="brand()"></app-delivery>
  <app-closing></app-closing>
</main>

<app-footer [brand]="brand()"></app-footer>

<app-cart-drawer [open]="cartOpen()" (closeDrawer)="closeCart()" (checkout)="openCheckout()"></app-cart-drawer>
<app-checkout-modal [open]="checkoutOpen()" (closeModal)="closeCheckout()"></app-checkout-modal>
<app-toast-stack></app-toast-stack>

// frontend/src/App.jsx
import React, { useEffect, useState } from 'react';

import api from './api/client.js';
import { FALLBACK_BRAND } from './api/fallbackData.js';

import useScrollPhysics from './hooks/useScrollPhysics.js';
import useReveal from './hooks/useReveal.js';

import Navbar from './components/common/Navbar.jsx';
import Instruments from './components/common/Instruments.jsx';
import SnapDots from './components/common/SnapDots.jsx';
import Footer from './components/common/Footer.jsx';

import Hot from './components/sections/Hot.jsx';
import Dry from './components/sections/Dry.jsx';
import Turn from './components/sections/Turn.jsx';
import Relief from './components/sections/Relief.jsx';
import Manifesto from './components/sections/Manifesto.jsx';
import WhyOxyra from './components/sections/WhyOxyra.jsx';
import Products from './components/sections/Products.jsx';
import Club from './components/sections/Club.jsx';
import Testimonials from './components/sections/Testimonials.jsx';
import LabReport from './components/sections/LabReport.jsx';
import Delivery from './components/sections/Delivery.jsx';
import Closing from './components/sections/Closing.jsx';

export default function App() {
  const [brand, setBrand] = useState(FALLBACK_BRAND);
  const { temperature, gaugePercent, activeSection, crystallized, dotsVisible } = useScrollPhysics();

  useEffect(() => {
    let active = true;
    api.getBrand().then((data) => {
      if (active) setBrand(data);
    });
    return () => {
      active = false;
    };
  }, []);

  useEffect(() => {
    document.title = `${brand.name} — ${brand.tagline}`;
  }, [brand]);

  // Re-run the reveal-on-scroll observer once the static (non-fetched)
  // sections have mounted.
  useReveal([]);

  return (
    <>
      <Navbar brand={brand} />
      <Instruments temperature={temperature} gaugePercent={gaugePercent} />
      <SnapDots activeSection={activeSection} visible={dotsVisible} />

      <main>
        <Hot />
        <Dry />
        <Turn />
        <Relief crystallized={crystallized} />
        <Manifesto />
        <WhyOxyra />
        <Products />
        <Club />
        <Testimonials />
        <LabReport />
        <Delivery brand={brand} />
        <Closing />
      </main>

      <Footer brand={brand} />
    </>
  );
}
