// frontend/src/components/common/Instruments.jsx
import React from 'react';

/**
 * @param {{ temperature: string, gaugePercent: number }} props
 */
export default function Instruments({ temperature, gaugePercent }) {
  return (
    <>
      <div id="temp-pill">{temperature}</div>
      <div id="gauge">
        <div id="gauge-fill" style={{ height: `${gaugePercent}%` }} />
      </div>
      <div id="mock-label">MOCK · DATA ILUSTRASI · INTERNAL</div>
    </>
  );
}

// frontend/src/app/shared/instruments.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-instruments',
  standalone: true,
  template: `
    <div id="temp-pill">{{ temperature }}</div>
    <div id="gauge">
      <div id="gauge-fill" [style.height.%]="gaugePercent"></div>
    </div>
    <div id="mock-label">MOCK · DATA ILUSTRASI · INTERNAL</div>
  `,
})
export class InstrumentsComponent {
  @Input({ required: true }) temperature!: string;
  @Input({ required: true }) gaugePercent!: number;
}
